# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'eTicket' do
    rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'

    # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    # Add new pods below this line
    pod 'React', path: rn_path, subspecs: [
      'RCTImage',
    ]
# Add new pods below this line
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Messaging', '~> 5.3.0'
# Add new pods below this line

pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
# Add new pods below this line
pod 'RNSVG', :path => '../node_modules/react-native-svg'
# Add new pods below this line

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == "React"
                target.remove_from_project
            end
        end
    end

end
