# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'eTicket' do
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'RCTImage',
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Messaging', '~> 5.3.0'
pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
pod 'RNSVG', :path => '../node_modules/react-native-svg'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
end
