# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'eTicket' do
    rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'

    # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
    pod 'React', path: rn_path, subspecs: [
        'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation',
      'RCTImage',
    ]
     # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
# Add new pods below this line
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Messaging', '~> 5.3.0'
# Add new pods below this line
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
# Add new pods below this line
pod 'RNSVG', :path => '../node_modules/react-native-svg'
# Add new pods below this line

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == "React"
                target.remove_from_project
            end
        end
    end

end
